# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2670523aed8deb6969a8174d5b039c61d5fe6630306cb8cd137e1fcd39ce61bffa9e20682b6903ca43131f57a63f99fa049f78b0900b763ee1875757f3809dab

test:
  secret_key_base: 775ce08f37e8eba3fff60c5996a1db7b1e890299fd226f80d915492f7d06f6e1852feb7785b6f4ff44ddb1f10b187c129c6bafa69b02dce61584017d6156de81

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
